import type {
  ExternalLinks,
  Experience,
  PortfolioProject,
  Skills,
} from "./types";

export const externalLinks: ExternalLinks = {
  github: "https://github.com/jillo-abdullahi",
  linkedIn: "https://www.linkedin.com/in/jilloabdullahi/",
  twitter: "https://x.com/shrewd_turtle",
  facebook: "https://www.facebook.com/p/Shrewd-Turtle-61570536062535/",
  stackoverflow: "https://stackoverflow.com/users/7300926/jillo-abdullahi",
  repositories: "https://github.com/jillo-abdullahi?tab=repositories",
  instagram: "https://www.instagram.com/jillo_woche/",
  calLink: "https://cal.com/jillowoche/15min",
  email: "jayloabdullahi@gmail.com",
  telegram: "https://t.me/shrewdTurtle",
};

export const experiences: Experience[] = [
  {
    isCurrent: true,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "GasHawk",
    companyUrl: "https://www.linkedin.com/company/gashawk/",
    companyLogo: "gashawkLogo.jpeg",
    location: "Remote",
    date: "2024 - 2025",
    description: [
      "Rebuilt and redesigned the core web application (React, TypeScript), improving reliability and reducing load times for a smoother user experience.",
      "Implemented a secure authentication system and optimized REST APIs, cutting latency and eliminating recurring timeout errors.",
      "Developed multi-chain interoperability and a quota plan system, enabling seamless support across multiple EVM-compatible networks.",
      "Enhanced the Framer-powered marketing site with a streamlined gas savings checker, increasing developer engagement and improving product visibility.",
    ],
    technologies: [
      "React",
      "Chakra UI",
      "Zustand",
      "TypeScript",
      "Wagmi",
      "ethers.js",
      "Express.js",
      "Postgres",
      "Framer",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "IOTA",
    companyUrl: "https://www.linkedin.com/company/iotafoundation/",
    companyLogo: "iotaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2023 - 2024",
    description: [
      "Built backend systems to automate the exchange of SPS documents between IOTA and partners, reducing manual steps and improving process reliability.",
      "Revamped the TLIP web app frontend with React and TypeScript, enhancing usability and delivering a smoother, more responsive user experience.",
    ],
    technologies: ["React", "TypeScript", "DynamoDB", "Express.js", "RabbitMQ"],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "Syndicate",
    companyUrl: "https://www.linkedin.com/company/syndicate-protocol/",
    companyLogo: "syndicateLogo.jpeg",
    location: "Remote",
    date: "2021 - 2023",
    description: [
      "Built and deployed a production-ready Web3 dApp in under 3 months (TypeScript, React, Ethereum/Polygon), accelerating Syndicate's go-to-market timeline.",
      "Launched Collectives, enabling NFT-based communities to organize around generative art and driving early engagement among creators and collectors.",
      "Designed and delivered a GraphQL backend for storing off-chain data in just one month, improving data accessibility and reducing integration complexity.",
      "Increased smart contract reliability by implementing a comprehensive automated testing suite, reducing the risk of regressions and strengthening security.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "GraphQL",
      "TailwindCSS",
      "Redux",
      "Postgres",
      "Solidity",
      "ethers.js",
      "Metamask",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Front-end Software Engineer",
    company: "Cellulant",
    companyUrl: "https://www.linkedin.com/company/cellulant/",
    companyLogo: "cellulantLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2019 - 2021",
    description: [
      "Improved accessibility and usability of payment apps by redesigning flows in React/Next.js.",
      "Optimized checkout UX across 6+ payment options, leading to smoother transaction completion.",
    ],
    technologies: ["React", "Redux", "Next.js", "TypeScript", "Express.js"],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "Andela",
    companyUrl: "https://www.linkedin.com/company/andela/",
    companyLogo: "andelaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2018 - 2019",
    description: [
      "Delivered multiple front-end applications with ReactJS on tight sprint cycles, enabling faster product iterations and improving user experience.",
      "Developed and deployed a REST API with Python/Django that supported scalable data handling and reduced backend response times under production load.",
    ],
    technologies: ["React", "TypeScript", "Django", "Postgres"],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Team Leader",
    company: "Sama",
    companyUrl: "https://www.linkedin.com/company/sama-ai/",
    companyLogo: "samaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2016 - 2018",
    description: [
      "Led a 22-person team in executing a large-scale web crawling project for Glassdoor.",
      "Coordinated workflows, evaluated team performance, and delivered constructive feedback that improved accuracy and efficiency.",
    ],
    technologies: [
      "JavaScript",
      "HTML/CSS",
      "Ms Excel",
      "Regular Expressions",
      "Xpath",
    ],
  },
  {
    isCurrent: false,
    type: "education",
    title: "Bachelor of Science in Information Technology",
    company: "Jomo Kenyatta University of Agriculture and Technology",
    companyUrl: "https://www.linkedin.com/school/jkuat/",
    companyLogo: "jkuatLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2012 - 2015",
    description: ["Graduated with First Class Honors."],
  },
];

export const portfolioProjects: PortfolioProject[] = [
  {
    title: "dApp for managing GasHawk transactions",
    description:
      "GasHawk is saving retails and institutions up to 95% on transaction gas fees on Ethereum, Optimism, and Base.",
    image: "gashawk.png",
    preview: "https://app.gashawk.io/",
    stacks: ["React", "Vite", "Chakra UI", "TypeScript", "Express.js"],
    completed: true,
  },
  {
    title: "Ballot dApp for decentralized voting",
    description:
      "A modern, decentralized voting platform built on Ethereum that enables communities to create and vote on proposals.",
    image: "ballot.png",
    preview: "https://ballot-box-green.vercel.app/",
    github: "https://github.com/jillo-abdullahi/ballotBox",
    contract: "https://github.com/jillo-abdullahi/ballotBox-contracts",
    stacks: ["React", "Vite", "TailwindCSS", "TypeScript", "Wagmi", "Viem"],
    completed: true,
  },
  {
    title: "A link sharing app for developers",
    description:
      "A fully-functional link-sharing app for developers. You can now consolidate and share your links to different platforms with just one URL.",
    image: "devlinks.png",
    preview: "https://my-links-amber.vercel.app/",
    github: "https://github.com/jillo-abdullahi/my-links",
    stacks: ["Nest.js", "Vue.js", "TailwindCSS", "TypeScript", "Postgres"],
    completed: true,
  },
  {
    title: "Memory Game",
    description:
      "A fun memory game where players try to match pairs against each other or against the CPU.",
    image: "memory.png",
    preview: "https://memory-game-green-nine.vercel.app/",
    github: "https://github.com/jillo-abdullahi/memory-game",
    stacks: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
  },
  {
    title: "Dictionary web app solution",
    description:
      "A dictionary web app built with TailwindCSS and Next.js. It uses a free Dictionary API to fetch data for the searched word. It also uses the Web Speech API to play the audio file for the searched word.",
    image: "dictionary.png",
    preview: "https://dictionary-web-app-ashy.vercel.app/",
    github: "https://github.com/jillo-abdullahi/dictionary-web-app",
    stacks: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
  },
  {
    title: "Advanced Rock Paper Scissors",
    description:
      "A Rock, Paper, Scissors, Lizard, Spock game you can play against the CPU.",
    image: "rockPaperScissors.png",
    preview: "https://advanced-rock-paper-scissors.vercel.app/",
    github: "https://github.com/jillo-abdullahi/advanced-rock-paper-scissors",
    stacks: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
  },
];

export const skills: Skills = {
  backend: [
    { name: "Express.js", level: "85%" },
    { name: "GraphQL", level: "90%" },
    { name: "Nest.js", level: "89%" },
    { name: "Django", level: "60%" },
    { name: "Flask", level: "50%" },
  ],
  frontend: [
    { name: "React", level: "90%" },
    { name: "Next.js", level: "85%" },
    { name: "Vue.js", level: "80%" },
    { name: "TailwindCSS", level: "90%" },
    { name: "Chakra UI", level: "85%" },
  ],
  databases: [
    { name: "Postgres", level: "82%" },
    { name: "MySQL", level: "75%" },
    { name: "Google Firestore", level: "80%" },
    { name: "SQLite", level: "70%" },
    { name: "DynamoDB", level: "80%" },
  ],
  // devops: [
  //   { name: "Docker", level: "80%" },
  //   { name: "Firebase", level: "70%" },
  //   { name: "Github Actions", level: "80%" },
  //   { name: "Vercel", level: "80%" },
  //   { name: "CircleCI", level: "60%" },
  // ],
  web3: [
    { name: "Wagmi", level: "85%" },
    { name: "ethers.js", level: "85%" },
    { name: "Foundry", level: "70%" },
    { name: "Viem", level: "80%" },
    { name: "WalletConnect", level: "85%" },
  ],
};
