import type {
  ExternalLinks,
  Experience,
  PortfolioProject,
  Skills,
} from "./types";

export const externalLinks: ExternalLinks = {
  github: "https://github.com/jillo-abdullahi",
  linkedIn: "https://www.linkedin.com/in/jilloabdullahi/",
  twitter: "https://x.com/shrewd_turtle",
  facebook: "https://www.facebook.com/p/Shrewd-Turtle-61570536062535/",
  stackoverflow: "https://stackoverflow.com/users/7300926/jillo-abdullahi",
  repositories: "https://github.com/jillo-abdullahi?tab=repositories",
  instagram: "https://www.instagram.com/jillo_woche/",
  calLink: "https://cal.com/jillowoche/15min",
  email: "jayloabdullahi@gmail.com",
};

export const experiences: Experience[] = [
  {
    isCurrent: true,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "GasHawk",
    companyUrl: "https://www.linkedin.com/company/gashawk/",
    companyLogo: "gashawkLogo.jpeg",
    location: "Remote",
    date: "2024 - present",
    description: [
      "Spearheaded the complete redesign and rebuild of the GasHawk web application, leveraging TypeScript, React, and Node.js to deliver a significantly enhanced user experience.",
      "Engineered and integrated critical features across the entire stack, such as multi-chain interoperability, a comprehensive quota plan system, and efficient session transfer functionalitys, thereby elevating user engagement and satisfaction.",
      "Redesigned savings calculator on the company Framer site, leading to increased user interaction and higher conversion rates.",
    ],
    technologies: [
      "React",
      "Chakra UI",
      "Zustand",
      "TypeScript",
      "Wagmi",
      "ethers.js",
      "Express.js",
      "Postgres",
      "Framer",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "IOTA",
    companyUrl: "https://www.linkedin.com/company/iotafoundation/",
    companyLogo: "iotaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2023 - 2024",
    description: [
      "Developed backend systems to automate exchange of SPS documents between IOTA and its partners making the process more efficient.",
      "Significantly improved the user experience of the IOTA TLIP web app by revamping the front-end using React and TypeScript.",
    ],
    technologies: ["React", "TypeScript", "DynamoDB", "Express.js", "RabbitMQ"],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "Syndicate",
    companyUrl: "https://www.linkedin.com/company/syndicate-protocol/",
    companyLogo: "syndicateLogo.jpeg",
    location: "Remote",
    date: "2021 - 2023",
    description: [
      "Successfully built (from the ground up) and deployed a performant web3 dApp within 3 months using TypeScript and React on the Ethereum and Polygon chains.",
      "Built and launched Collectives, a dApp feature focused on creating communities around generative art NFTs.",
      "Collaborated with team members to develop and deploy a GraphQL back-end API to store off-chain data within a month.",
      "Wrote robust tests for the existing smart contracts to ensure reliability and security.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "GraphQL",
      "TailwindCSS",
      "Redux",
      "Postgres",
      "Solidity",
      "ethers.js",
      "Metamask",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Front-end Software Engineer",
    company: "Cellulant",
    companyUrl: "https://www.linkedin.com/company/cellulant/",
    companyLogo: "cellulantLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2019 - 2021",
    description: [
      "Worked closely with the design team to dramatically improve the accessibility and user-friendliness of applications with React and NextJS.",
      "Continuously iterated over front-end web apps and used observation tools like Hotjar to significantly improve user payment flows for over 6 payment options.",
    ],
    technologies: ["React", "Redux", "Next.js", "TypeScript", "Express.js"],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Full Stack Software Engineer",
    company: "Andela",
    companyUrl: "https://www.linkedin.com/company/andela/",
    companyLogo: "andelaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2018 - 2019",
    description: [
      "Collaborated with the design team to quickly and efficiently build front-end apps using ReactJS.",
      "Collaborated with team members to build and deploy a performant REST API using Python/Django within a month.",
      "Worked with the team to improve the codebase and overall product quality.",
    ],
    technologies: ["React", "TypeScript", "Django", "Postgres"],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Team Leader",
    company: "Sama",
    companyUrl: "https://www.linkedin.com/company/sama-ai/",
    companyLogo: "samaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2016 - 2018",
    description: [
      "Supervised and coordinated the work efforts of a team of 22 leading to the success of a major pilot project.",
      "Ensured that the allocated work is done professionally as per the required standards and targets as defined and desired by Sama.",
      "Ensured that the team is motivated and that the team members are working in harmony.",
      "Closely worked with the training and quality departments to achieve targeted SLAs.",
    ],
    technologies: [
      "JavaScript",
      "HTML/CSS",
      "Ms Excel",
      "Regular Expressions",
      "Xpath",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    title: "Quality Analyst",
    company: "Sama",
    companyUrl: "https://www.linkedin.com/company/sama-ai/",
    companyLogo: "samaLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2015 - 2016",
    description: [
      "Analyzed the levels of quality of work in the different Sama work streams, measuring compliance against set standards and recommending actions to be taken to improve quality based on assessment findings.",
      "Assessed agents transactions and advised on required measures to improve quality.",
      "Compiled and sent reports to the training and quality manager and to other relevant stakeholders and ensured that each work stream is consistently delivering standard work.",
    ],
    technologies: [
      "JavaScript",
      "HTML/CSS",
      "Ms Excel",
      "Regular Expressions",
      "Xpath",
    ],
  },
  {
    isCurrent: false,
    type: "education",
    title: "Bachelor of Science in Information Technology",
    company: "Jomo Kenyatta University of Agriculture and Technology",
    companyUrl: "https://www.linkedin.com/school/jkuat/",
    companyLogo: "jkuatLogo.jpeg",
    location: "Nairobi, Kenya",
    date: "2012 - 2015",
    description: [
      "Comprehensive technology education.",
      "In-demand Skills.",
      "Problem solving and innovation.",
      "Collaboration and communication",
    ],
  },
];

export const portfolioProjects: PortfolioProject[] = [
  {
    title: "dApp for managing GasHawk transactions",
    description:
      "GasHawk is saving retails and institutions up to 95% on transaction gas fees on Ethereum, Optimism, and Base.",
    image: "gashawk.png",
    preview: "https://app.gashawk.io/",
    stacks: ["React", "Vite", "Chakra UI", "TypeScript", "Express.js"],
    completed: true,
  },
  {
    title: "Ballot dApp for decentralized voting",
    description:
      "A modern, decentralized voting platform built on Ethereum that enables communities to create and vote on proposals.",
    image: "ballot.png",
    preview: "https://ballot-box-green.vercel.app/",
    github: "https://github.com/jillo-abdullahi/ballotBox",
    stacks: ["React", "Vite", "TailwindCSS", "TypeScript", "Wagmi", "Viem"],
    completed: true,
  },
  {
    title: "A link sharing app for developers",
    description:
      "A fully-functional link-sharing app for developers. You can now consolidate and share your links to different platforms with just one URL.",
    image: "devlinks.png",
    preview: "https://my-links-amber.vercel.app/",
    github: "https://github.com/jillo-abdullahi/my-links",
    stacks: ["Nest.js", "Vue.js", "TailwindCSS", "TypeScript", "Postgres"],
    completed: true,
  },
  {
    title: "Memory Game",
    description:
      "A fun memory game where players try to match pairs against each other or against the CPU.",
    image: "memory.png",
    preview: "https://memory-game-green-nine.vercel.app/",
    github: "https://github.com/jillo-abdullahi/memory-game",
    stacks: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
  },
  {
    title: "Dictionary web app solution",
    description:
      "A dictionary web app built with TailwindCSS and Next.js. It uses a free Dictionary API to fetch data for the searched word. It also uses the Web Speech API to play the audio file for the searched word.",
    image: "dictionary.png",
    preview: "https://dictionary-web-app-ashy.vercel.app/",
    github: "https://github.com/jillo-abdullahi/dictionary-web-app",
    stacks: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
  },
  {
    title: "Advanced Rock Paper Scissors",
    description:
      "A Rock, Paper, Scissors, Lizard, Spock game you can play against the CPU.",
    image: "rockPaperScissors.png",
    preview: "https://advanced-rock-paper-scissors.vercel.app/",
    github: "https://github.com/jillo-abdullahi/advanced-rock-paper-scissors",
    stacks: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
  },
];

export const skills: Skills = {
  backend: [
    { name: "Express.js", level: "85%" },
    { name: "GraphQL", level: "90%" },
    { name: "Nest.js", level: "89%" },
    { name: "Django", level: "60%" },
    { name: "Flask", level: "50%" },
  ],
  frontend: [
    { name: "React", level: "90%" },
    { name: "Next.js", level: "85%" },
    { name: "Vue.js", level: "80%" },
    { name: "TailwindCSS", level: "90%" },
    { name: "Chakra UI", level: "85%" },
  ],
  databases: [
    { name: "Postgres", level: "82%" },
    { name: "MySQL", level: "75%" },
    { name: "Google Firestore", level: "80%" },
    { name: "SQLite", level: "70%" },
    { name: "DynamoDB", level: "80%" },
  ],
  // devops: [
  //   { name: "Docker", level: "80%" },
  //   { name: "Firebase", level: "70%" },
  //   { name: "Github Actions", level: "80%" },
  //   { name: "Vercel", level: "80%" },
  //   { name: "CircleCI", level: "60%" },
  // ],
  web3: [
    { name: "Wagmi", level: "85%" },
    { name: "ethers.js", level: "85%" },
    { name: "Foundry", level: "70%" },
    { name: "Viem", level: "80%" },
    { name: "WalletConnect", level: "85%" },
  ],
};
