import type {
  ExternalLinks,
  Experience,
  PortfolioProject,
  Skills,
  Testimonial,
} from "./types";
import { Spade, Fuel, Vote, Share2, Brain, BookOpen } from "lucide-react";

export const externalLinks: ExternalLinks = {
  github: "https://github.com/jillo-abdullahi",
  linkedIn: "https://linkedin.com/in/jilloabdullahi",
  twitter: "https://x.com/shrewd_turtle",
  facebook: "https://www.facebook.com/p/Shrewd-Turtle-61570536062535/",
  stackoverflow: "https://stackoverflow.com/users/7300926/jillo-abdullahi",
  repositories: "https://github.com/jillo-abdullahi?tab=repositories",
  instagram: "https://www.instagram.com/jillo_woche/",
  calLink: "https://calendar.app.google/UjK3FBKSAaX6jXvK6",
  email: "jayloabdullahi@gmail.com",
  telegram: "https://t.me/shrewdTurtle",
  sneakerHeadImage:
    "https://res.cloudinary.com/dsuhsqcb2/image/upload/f_auto,q_auto,w_512/v1763295450/sneakerhead985NoBg_wzya7p.webp",
};

export const currentlyInfo = {
  exploring: "Tanstack Start compared to Next.js",
  availableFor: "Full-time & contract opportunities",
};

export const experiences: Experience[] = [
  {
    isCurrent: true,
    type: "work",
    workType: "Full-time",
    title: "Senior Frontend Engineer (React)",
    company: "Rainforest Alliance",
    companyUrl: "https://www.linkedin.com/company/rainforest-alliance",
    companyLogo: "rainforestLogo.jpg",
    location: "Hybrid",
    startDate: "Oct 2025",
    description: [
      "Building responsive, accessible web applications with React and TypeScript to support sustainability initiatives and improve user engagement.",
      "Collaborating with cross-functional teams to design and implement new features that enhance the user experience and drive impact.",
    ],
    technologies: [
      "React",
      "TypeScript",
      "TailwindCSS",
      "Tanstack Query",
      "Tanstack Router",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Consultancy",
    title: "Full Stack Software Engineer",
    company: "GasHawk",
    companyUrl: "https://www.linkedin.com/company/gashawk/",
    companyLogo: "gashawkLogo.jpeg",
    location: "Remote",
    startDate: "Apr 2024",
    endDate: "Aug 2025",
    description: [
      "Rebuilt and redesigned the core web application (React, TypeScript), improving reliability and reducing load times for a smoother user experience.",
      "Implemented a secure authentication system and optimized REST APIs, cutting latency and eliminating recurring timeout errors.",
      "Developed multi-chain interoperability and a quota plan system, enabling seamless support across multiple EVM-compatible networks.",
      "Enhanced the Framer-powered marketing site with a streamlined gas savings checker, increasing developer engagement and improving product visibility.",
    ],
    technologies: [
      "React",
      "Chakra UI",
      "Zustand",
      "TypeScript",
      "Wagmi",
      "ethers.js",
      "Express.js",
      "Postgres",
      "Framer",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Consultancy",
    title: "Full Stack Software Engineer",
    company: "IOTA",
    companyUrl: "https://www.linkedin.com/company/iotafoundation/",
    companyLogo: "iotaLogo.jpeg",
    location: "Hybrid",
    startDate: "Nov 2023",
    endDate: "Apr 2024",
    description: [
      "Built backend systems to automate the exchange of SPS documents between IOTA and partners, reducing manual steps and improving process reliability.",
      "Revamped the TLIP web app frontend with React and TypeScript, enhancing usability and delivering a smoother, more responsive user experience.",
    ],
    technologies: ["React", "TypeScript", "DynamoDB", "Express.js", "RabbitMQ"],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Consultancy",
    title: "Full Stack Software Engineer",
    company: "Syndicate",
    companyUrl: "https://www.linkedin.com/company/syndicate-protocol/",
    companyLogo: "syndicateLogo.jpeg",
    location: "Remote",
    startDate: "Apr 2021",
    endDate: "Mar 2023",
    description: [
      "Built and deployed a production-ready Web3 dApp in under 3 months (TypeScript, React, Ethereum/Polygon), accelerating Syndicate's go-to-market timeline.",
      "Launched Collectives, enabling NFT-based communities to organize around generative art and driving early engagement among creators and collectors.",
      "Designed and delivered a GraphQL backend for storing off-chain data in just one month, improving data accessibility and reducing integration complexity.",
      "Increased smart contract reliability by implementing a comprehensive automated testing suite, reducing the risk of regressions and strengthening security.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "GraphQL",
      "TailwindCSS",
      "Redux",
      "Postgres",
      "Solidity",
      "ethers.js",
      "Metamask",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Full-time",
    title: "Front-end Software Engineer",
    company: "Cellulant",
    companyUrl: "https://www.linkedin.com/company/cellulant/",
    companyLogo: "cellulantLogo.jpeg",
    location: "On-site",
    startDate: "Nov 2019",
    endDate: "Apr 2021",
    description: [
      "Improved accessibility and usability of payment apps by redesigning flows in React/Next.js.",
      "Optimized checkout UX across 6+ payment options, leading to smoother transaction completion.",
    ],
    technologies: ["React", "Redux", "Next.js", "TypeScript", "Express.js"],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Full-time",
    title: "Full Stack Software Engineer",
    company: "Andela",
    companyUrl: "https://www.linkedin.com/company/andela/",
    companyLogo: "andelaLogo.jpeg",
    location: "On-site",
    startDate: "Nov 2018",
    endDate: "Nov 2019",
    description: [
      "Delivered multiple front-end applications with ReactJS on tight sprint cycles, enabling faster product iterations and improving user experience.",
      "Developed and deployed a REST API with Python/Django that supported scalable data handling and reduced backend response times under production load.",
    ],
    technologies: ["React", "TypeScript", "Django", "Postgres"],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Full-time",
    title: "Team Leader",
    company: "Sama",
    companyUrl: "https://www.linkedin.com/company/sama-ai/",
    companyLogo: "samaLogo.jpeg",
    location: "On-site",
    startDate: "Jun 2016",
    endDate: "Nov 2018",
    description: [
      "Led a 22-person team in executing a large-scale web crawling project for Glassdoor.",
      "Coordinated workflows, evaluated team performance, and delivered constructive feedback that improved accuracy and efficiency.",
    ],
    technologies: [
      "JavaScript",
      "HTML/CSS",
      "Ms Excel",
      "Regular Expressions",
      "Xpath",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Full-time",
    title: "Quality Analyst",
    company: "Sama",
    companyUrl: "https://www.linkedin.com/company/sama-ai/",
    companyLogo: "samaLogo.jpeg",
    location: "On-site",
    startDate: "Nov 2015",
    endDate: "May 2016",
    description: [
      "Improved quality across multiple work streams by analyzing compliance gaps and recommending corrective actions.",
      "Boosted agent performance by assessing transactions, giving feedback, and driving measurable quality gains.",
      "Delivered clear quality reports to managers and stakeholders, ensuring consistent performance standards.",
    ],
    technologies: [
      "JavaScript",
      "HTML/CSS",
      "Ms Excel",
      "Regular Expressions",
      "Xpath",
    ],
  },
  {
    isCurrent: false,
    type: "work",
    workType: "Full-time",
    title: "Agent Junior Developer",
    company: "Sama",
    companyUrl: "https://www.linkedin.com/company/sama-ai/",
    companyLogo: "samaLogo.jpeg",
    location: "On-site",
    startDate: "July 2015",
    endDate: "Nov 2015",
    description: [
      "Optimized and maintained client job feeds using HTML, CSS, XPaths, and regular expressions, ensuring accurate integrations and reliable updates.",
      "Streamlined error resolution processes by reviewing feed issues, escalating complex cases, and recommending improvements that enhanced data quality and detection.",
      "Delivered consistent, high-quality results in a fast-paced environment by verifying large data volumes, eliminating duplication, and supporting overall team performance.",
    ],
    technologies: [
      "JavaScript",
      "HTML/CSS",
      "Ms Excel",
      "Regular Expressions",
      "Xpath",
    ],
  },
  {
    isCurrent: false,
    type: "education",
    title: "Bachelor of Science in Information Technology",
    company: "Jomo Kenyatta University of Agriculture and Technology",
    companyUrl: "https://www.linkedin.com/school/jkuat/",
    companyLogo: "jkuatLogo.jpeg",
    location: "On-site",
    startDate: "Jan 2012",
    endDate: "Jan 2015",
    description: ["Graduated with First Class Honors."],
    isEducational: true,
  },
];

export const portfolioProjects: PortfolioProject[] = [
  {
    title: "Poker planning app for remote teams and agile squads",
    description:
      "A collaborative poker planning application designed to help remote teams and agile squads estimate project tasks effectively.",
    moreDetails:
      "Teams create rooms, invite members, and use virtual cards to estimate tasks in real-time. The app supports various estimation techniques and provides analytics to track team performance over time.",
    image:
      "https://res.cloudinary.com/dsuhsqcb2/image/upload/v1769077140/portfolioImages/votedeck_qc55sh.png",
    preview: "https://votedeck.vercel.app",
    stacks: [
      "Fastify",
      "Socket.io",
      "Redis",
      "Postgres",
      "React",
      "Vite",
      "TailwindCSS",
      "TypeScript",
    ],
    completed: true,
    github: "https://github.com/jillo-abdullahi/votedeck",
    contract: "https://github.com/jillo-abdullahi/votedeck-api",
    category: "Full Stack",
    demoButtonText: "Start Planning",
    demoButtonIcon: Spade,
  },
  {
    title: "Ethereum dApp for managing GasHawk transactions",
    description:
      "GasHawk is saving retails and institutions up to 95% on transaction gas fees on Ethereum, Optimism, and Base.",
    moreDetails:
      "Users connect their wallet, choose network, and GasHawk routes transactions through its relay to minimize gas. The dashboard shows queued, mined, and failed txs with live status updates.",
    image:
      "https://res.cloudinary.com/dsuhsqcb2/image/upload/v1769077537/portfolioImages/gasHawk_qkug8r.png",
    preview: "https://app.gashawk.io/",
    stacks: [
      "Express.js",
      "React",
      "Vite",
      "Chakra UI",
      "TypeScript",
      "Postgres",
    ],
    completed: true,
    category: "Web3",
    demoButtonText: "Use GasHawk",
    demoButtonIcon: Fuel,
  },
  {
    title: "Ballot app for decentralized voting",
    description:
      "A modern, decentralized voting platform built on Ethereum that enables communities to create and vote on proposals.",
    moreDetails:
      "Proposers connect their wallet and open proposals. Voters connect wallets to cast on-chain votes; the UI watches contract events to show tallies and closes automatically when the voting period ends.",
    image:
      "https://res.cloudinary.com/dsuhsqcb2/image/upload/v1769075456/portfolioImages/ballot_ynqhgh.png",
    preview: "https://ballot-box-green.vercel.app/",
    github: "https://github.com/jillo-abdullahi/ballotBox",
    contract: "https://github.com/jillo-abdullahi/ballotBox-contracts",
    stacks: ["React", "Vite", "Solidity", "TailwindCSS", "TypeScript", "Wagmi"],
    completed: true,
    category: "Web3",
    demoButtonText: "Use Ballot",
    demoButtonIcon: Vote,
  },
  {
    title: "A link sharing app for developers",
    description:
      "A link-sharing app for developers. You can now consolidate and share your links to different platforms with just one URL.",
    moreDetails:
      "Users authenticate, add platform handles and custom links, and the app generates a single public profile URL. Visitors see a responsive card grid with the option to copy links or visit external sites.",
    image:
      "https://res.cloudinary.com/dsuhsqcb2/image/upload/v1769075456/portfolioImages/devlinks_nze4ir.png",
    preview: "https://my-links-amber.vercel.app/",
    github: "https://github.com/jillo-abdullahi/my-links",
    stacks: ["Nest.js", "Vue.js", "TailwindCSS", "TypeScript", "Postgres"],
    completed: true,
    category: "Full Stack",
    demoButtonText: "Use DevLinks",
    demoButtonIcon: Share2,
  },
  {
    title: "Memory Game",
    description:
      "A fun memory game where players try to match pairs against each other or against the CPU.",
    moreDetails:
      "Players choose board size and mode (solo, vs CPU, or head-to-head). Cards flip, turns alternate, and scores update in real time until all pairs are matched, then a results modal invites a rematch.",
    image:
      "https://res.cloudinary.com/dsuhsqcb2/image/upload/v1769075457/portfolioImages/memory_gbwjvc.png",
    preview: "https://memory-game-green-nine.vercel.app/",
    github: "https://github.com/jillo-abdullahi/memory-game",
    stacks: ["TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
    category: "Frontend",
    demoButtonIcon: Brain,
    demoButtonText: "Play Memory Game",
  },
  {
    title: "Dictionary web app solution",
    description:
      "A dictionary web app built with TailwindCSS and Next.js. It uses a free Dictionary API to fetch data for the searched word. It also uses the Web Speech API to play the audio file for the searched word.",
    moreDetails:
      "Users search a term, the app fetches multiple definitions, phonetics, and examples from the API, and provides a one-click audio pronunciation via the Web Speech API. Theme toggles and responsive layout keep it readable everywhere.",
    image:
      "https://res.cloudinary.com/dsuhsqcb2/image/upload/v1769075456/portfolioImages/dictionary_prq9mn.png",
    preview: "https://dictionary-web-app-ashy.vercel.app/",
    github: "https://github.com/jillo-abdullahi/dictionary-web-app",
    stacks: ["TypeScript", "Next.js", "TailwindCSS"],
    completed: true,
    category: "Frontend",
    demoButtonIcon: BookOpen,
    demoButtonText: "Use Dictionary",
  },
];

export const skills: Skills = {
  backend: [
    { name: "Express.js/Fastify", level: "90%" },
    { name: "Apollo GraphQL", level: "80%" },
    { name: "Nest.js", level: "70%" },
    { name: "Django", level: "60%" },
    { name: "Flask", level: "50%" },
  ],
  frontend: [
    { name: "Vite/Next.js", level: "90%" },
    { name: "Tanstack Query/Router", level: "90%" },
    { name: "Redux/Zustand", level: "90%" },
    { name: "Tailwind/ChakraUI", level: "90%" },
    { name: "Vue.js", level: "80%" },
  ],
  "databases/devops": [
    { name: "Prisma ORM", level: "80%" },
    { name: "Google Firebase", level: "80%" },
    { name: "Supabase", level: "75%" },
    { name: "Docker", level: "70%" },
    { name: "Github Actions", level: "60%" },
  ],
  web3: [
    { name: "Wagmi", level: "85%" },
    { name: "ethers.js", level: "85%" },
    { name: "Viem", level: "85%" },
    { name: "WalletConnect", level: "85%" },
    { name: "Foundry", level: "70%" },
  ],
};

export const testimonials: Testimonial[] = [
  {
    name: "Dr. Daniel Pfeffer",
    linkedInUrl: "https://www.linkedin.com/in/daniel-pfeffer/",
    image: "daniel.jpeg",
    role: "Co-founder and CTO",
    date: "July 31, 2025",
    level: "Directly managed Jillo",
    bgImage: "testimonial-bg.svg",
    company: "GasHawk",
    quote: [
      "I had the pleasure of working with Jillo Woche at GasHawk, where he was our go-to Web Developer from April 2024 to August 2025. During that time, he made a massive impact across both the frontend and backend of our product.",
      "Jillo fully refactored our web application (React with ChakraUI) and significantly elevated the user experience with a keen eye for design language and user flow. On the backend, he contributed to our Node.js codebase, working with REST APIs (OpenAPI) and WebSockets - bringing clarity and quality to the entire stack.",
      "What stood out most was Jillo's ability to translate vague feature ideas into actionable tasks and even go beyond the brief to improve our product. He worked seamlessly across the frontend, backend, and leadership teams - bringing smart ideas, strong execution, and high-quality code to everything he touched. His pull request reviews were thoughtful and often included insights that benefited the whole team.",
      'Jillo doesn\'t just "do the job"- he owns it. He operates with autonomy, yet never in a silo. Communication was always crisp, feedback loops short, and his drive to iterate quickly without sacrificing quality made him a very valuable asset of our development efforts.',
      "He's a fantastic hire for any team looking for a versatile, proactive, and high-impact developer. While he's currently working in the web3 space, his skills and mindset are broadly applicable across any tech stack or industry.",
      "Highly recommended!",
    ],
  },
  {
    name: "Nathan Hausman",
    linkedInUrl: "https://www.linkedin.com/in/nathan-hausman/",
    role: "Senior Security Engineer",
    image: "nathan.jpeg",
    date: "March 7, 2023",
    bgImage: "testimonial2-bg.svg",
    level: "Directly managed Jillo",
    company: "AWS",
    quote: [
      "Jillo's positive attitude resonates across the engineering teams he works on! In addition to being a great fullstack engineer technically, Jillo is never afraid to take on new project scope and is able to energize those around him towards action.",
      "During his 2 year tenure on my team, Jillo successfully lead the development of numerous new components and user flows and ensured the quality of his work and those around him. In short, you'd be lucky to have Jillo on your team!",
    ],
  },
];
